CREATE TABLE authors
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(100)                             NOT NULL,
    last_name VARCHAR(100)                             NOT NULL,
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE books
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(150)                             NOT NULL,
    year             TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    language         VARCHAR(150)                             NOT NULL,
    total_copies     INTEGER                                  NOT NULL,
    status           VARCHAR(150)                             NOT NULL,
    available_copies INTEGER                                  NOT NULL,
    author_id        INTEGER                                  NOT NULL,
    publisher_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE fines
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount    INTEGER,
    reason    VARCHAR(255),
    type      VARCHAR(255),
    member_id INTEGER,
    loan_id   INTEGER,
    CONSTRAINT pk_fines PRIMARY KEY (id)
);

CREATE TABLE loans
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    due_date    TIMESTAMP WITHOUT TIME ZONE,
    return_date TIMESTAMP WITHOUT TIME ZONE,
    loan_date   TIMESTAMP WITHOUT TIME ZONE,
    staff_id    INTEGER,
    CONSTRAINT pk_loans PRIMARY KEY (id)
);

CREATE TABLE members
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    email             VARCHAR(255),
    phone             VARCHAR(255),
    address           VARCHAR(255),
    member_ship_level VARCHAR(255),
    status            VARCHAR(255),
    CONSTRAINT pk_members PRIMARY KEY (id)
);

CREATE TABLE publishers
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    address VARCHAR(255),
    CONSTRAINT pk_publishers PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status    VARCHAR(255),
    member_id INTEGER,
    book_id   INTEGER,
    CONSTRAINT pk_reservations PRIMARY KEY (id)
);

CREATE TABLE staffs
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    last_name VARCHAR(255),
    role      VARCHAR(255),
    CONSTRAINT pk_staffs PRIMARY KEY (id)
);

ALTER TABLE loans
    ADD CONSTRAINT uc_loans_staff UNIQUE (staff_id);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_PUBLISHER FOREIGN KEY (publisher_id) REFERENCES publishers (id);

ALTER TABLE fines
    ADD CONSTRAINT FK_FINES_ON_LOAN FOREIGN KEY (loan_id) REFERENCES loans (id);

ALTER TABLE fines
    ADD CONSTRAINT FK_FINES_ON_MEMBER FOREIGN KEY (member_id) REFERENCES members (id);

ALTER TABLE loans
    ADD CONSTRAINT FK_LOANS_ON_STAFF FOREIGN KEY (staff_id) REFERENCES staffs (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE reservations
    ADD CONSTRAINT FK_RESERVATIONS_ON_MEMBER FOREIGN KEY (member_id) REFERENCES members (id);